pipeline {
  agent {
  	docker {
  		image 'node:6-alpine'
  		args '-p 3000:3000'
  	}
  }
  environment {
    CI = 'true'
  }
  stages {
    stage('Build') {
      steps {
        echo 'Building...'
        echo "Running ${env.BUILD_ID} ${env.BUILD_DISPLAY_NAME} on ${env.NODE_NAME} and JOB ${env.JOB_NAME}"
        echo 'Build react'
        sh script:'''
          #!/bin/bash
          cd ./react2
          rm -rf node_modules/
          rm package-lock.json 
          npm install
          npm run build
          ls
          cd ./build
          ls -la
        '''
      }
    }
    stage('Test') {
      steps {
        echo 'Testing...'
      }
    }
    stage('Deploy') {
      steps {
        echo 'Deploying...'
      }
    }
    // stage('Restart all docker service') {
    //   steps {
    //     sh './scripts/restart_docker_service.sh'
    //   }
    // }
  }
}